config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :toernoois
  resources :deelnemers

  #aanmelden
  get "/aanmelden" => "aanmelden#index"
  get "/aanmelden/:id" => "aanmelden#new"
  post "/aanmelden" => "aanmelden#create"
  get "/thx" => "aanmelden#thx"

  #inschrijven
  get "/inschrijven/:id" => "inschrijven#new"
  post "/inschrijven/:id" => "inschrijven#create"
  get "/inschrijven" => "inschrijven#destroy"

  #indelen
  get "/indelen/:toernooiid" => "indelen#index"
  get "/indelen/:toernooiid/groep/:groepnummer" => "indelen#show"
  get "/indelen/:toernooiid/score" => "indelen#score"
  get "/indelen/:toernooiid/uitslag" => "indelen#uitslag"
  post "/indelen/:toernooiid" => "indelen#addingroep"
  post "/invoeren" => "indelen#invoeren"
  get "/indelen/:toernooiid/print" => "indelen#print"
  get "indelen/:toernooiid/tussenstand" => "indelen#tussenstand"

  root 'application#toernoois'
  get "/toernoois/:id/partijs" => "toernoois#partijs"

end

app/models/deelnemer.rb
class Deelnemer < ApplicationRecord
  validates :voornaam, :achternaam, :geboortedatum, :geslacht, presence: true

  has_and_belongs_to_many :toernoois
  has_and_belongs_to_many :groeps

  has_many :partijs, foreign_key: "witspeler_id", dependent: :destroy
  has_many :partijs, foreign_key: "zwartspeler_id", dependent: :destroy

  def naam
    "#{voornaam} #{tussenvoegsel + ' ' unless tussenvoegsel.empty?}#{achternaam}"
  end

  def effrating
    rating.nil?||rating.zero? ? 100 + (Time.now.year - geboortedatum.year) : rating
  end

end

app/controllers/deelnemers_controller.rb
class DeelnemersController < ApplicationController

  def index
    @deelnemers = Deelnemer.all
    @url = deelnemers_path
  end

  def show
    @deelnemer = Deelnemer.find(params[:id])
  end

  def new
    @deelnemer = Deelnemer.new
  end

  def create
    #Code copied in: inschrijven_controller.rb
    #Code copied in: aanmelden_controller.rb
    @deelnemer = Deelnemer.find_by(deelnemer_ess_params) || Deelnemer.new(deelnemer_params)
    
    @deelnemer.tussenvoegsel ||= ""
    @deelnemer.telefoonnummer ||= ""
    @deelnemer.knsbnummer ||= 0
    @deelnemer.rating ||= 0

    @deelnemer.email = params[:deelnemer][:email]
    @deelnemer.telefoonnummer = params[:deelnemer][:telefoonnummer]
    @deelnemer.knsbnummer = params[:deelnemer][:knsbnummer]
    @deelnemer.rating = params[:deelnemer][:rating]    
    
    if @deelnemer.save
      redirect_to deelnemers_path
    else
      render 'new'
    end

  end

  def edit
    @deelnemer = Deelnemer.find(params[:id])
  end

  def update
    @deelnemer = Deelnemer.find(params[:id])
    
    params[:deelnemer][:tussenvoegsel] ||= ""
    params[:deelnemer][:telefoonnummer] ||= ""
    params[:deelnemer][:telefoonnummer] ||= 0
    params[:deelnemer][:rating] ||= 0
    
    @deelnemer.update_attributes(deelnemer_params)
    if @deelnemer.save
      redirect_to :action => "index"
    else
      render :action => "edit"
    end

  end

  def destroy
    @deelnemer = Deelnemer.find(params[:id])
    @deelnemer.destroy
    redirect_to :action => "index"
  end

  # Code copied in: inschrijven_controller.rb
  # Code copied in: aanmelden_controller.rb
  private 

    def deelnemer_params
      params.require(:deelnemer).permit(:voornaam, :achternaam, :tussenvoegsel, :geboortedatum, :geslacht, :email, :telefoonnummer, :knsbnummer, :rating)
    end

    def deelnemer_update_params
      params.require(:deelnemer).permit(:email, :telefoonnummer, :knsbnummer, :rating)
    end

    def deelnemer_ess_params
      params.require(:deelnemer).permit(:voornaam, :tussenvoegsel, :achternaam, :geboortedatum, :geslacht)
    end

end

app/helpers/deelnemers_helper.rb
module DeelnemersHelper
end

app/views/deelnemers/_errors.html.erb
<% if @deelnemer.errors.any? %>
  <div style="border: 1px solid black">
    <h2><%= pluralize(@deelnemer.errors.count, "error") %> zijn gevonden:</h2>
 
    <ul>
    <% @deelnemer.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/deelnemers/_inschrijfform.html.erb
<%= form_for @deelnemer, url: @url do |f| %>
  <%= hidden_field_tag(:toernooi_id, @toernooi.id) unless @toernooi.nil? %>
  <%= hidden_field_tag(:redirect, @redirect||"deelnemers_path" ) %>

  <div class="input-field">
    <%= f.text_field(:voornaam) %>
    <label>Voornaam <i>(verplicht)</i></label>
  </div>

  <div class="input-field">
    <%= f.text_field(:tussenvoegsel) %>
    <label>Tussenvoegsel</label>
  </div>

  <div class="input-field">
    <%= f.text_field(:achternaam) %>
    <label>Achternaam <i>(verplicht)</i></label>
  </div>

  <div class="input-field">
    <%= f.text_field(:geboortedatum, class: "datepicker") %>
    <label>Geboortedatum <i>(verplicht)</i></label>
  </div>

  Geslacht <i>(verplicht)</i>:
  <br />

  <p>
    <%= f.radio_button :geslacht, "man" %>
    <%= f.label :geslacht_man, "Man" %>
  </p>
  <p>
    <%= f.radio_button :geslacht, "vrouw" %>
    <%= f.label :geslacht_vrouw, "Vrouw" %>
  </p>

  <div class="input-field">
    <%= f.text_field(:email) %>
    <label>Email</label>
  </div>

  <div class="input-field">
    <%= f.text_field(:telefoonnummer) %>
    <label>Telefoonnummer</label>
  </div>

  <div class="input-field">
    <%= f.text_field(:knsbnummer) %>
    <label>KNSB-nummer</label>
  </div>

  <div class="input-field">
    <%= f.text_field(:rating) %>
    <label>Rating</label>
  </div>

  <button class="btn waves-effect waves-light" type="submit" name="action">Verstuur
    <i class="material-icons right">send</i>
  </button>
<% end %>

app/views/deelnemers/edit.html.erb
<h1>Wijzig gegevens</h1>

<%= render partial:"inschrijfform" %>

app/views/deelnemers/index.html.erb
<h1>Alle Deelnemers:</h1>
<hr />

<% @deelnemers.each do |deelnemer| %>
  <% next if deelnemer.id == 1 %>
  <b>Naam: </b><%= deelnemer.naam %>
  <br />
  <b>Geboortedatum: </b><%= deelnemer.geboortedatum.strftime("%d-%m-%Y") %>
  <br />
  <b>E-mail: </b><%= deelnemer.email %>
  <br />
  <%= link_to "Laat zien", deelnemer %>
  <hr />
<% end %>

<br /><br />
<%= link_to "Voeg deelnemer toe", new_deelnemer_path %>

app/views/deelnemers/new.html.erb
<h1>Nieuwe Deelnemer: </h1>

<%= render partial:"/deelnemers/inschrijfform" %>
<br /><br />

<%= link_to "Alle Deelnemers", deelnemers_path %>

app/views/deelnemers/show.html.erb
<%= render partial: "/deelnemer", object: @deelnemer %>
<br /><br />
<%= link_to "Wijzig gegevens", edit_deelnemer_path(@deelnemer.id) %>
<br /><br />
<%= link_to "Alle Deelnemers", deelnemers_path %>
<br /><br />
<%= link_to "Verwijder deze Deelnemer", @deelnemer, method: :delete, data: {confirm: "Zeker weten?"} %>