config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :toernoois
  resources :deelnemers

  #aanmelden
  get "/aanmelden" => "aanmelden#index"
  get "/aanmelden/:id" => "aanmelden#new"
  post "/aanmelden" => "aanmelden#create"
  get "/thx" => "aanmelden#thx"

  #inschrijven
  get "/inschrijven/:id" => "inschrijven#new"
  post "/inschrijven/:id" => "inschrijven#create"
  get "/inschrijven" => "inschrijven#destroy"

  #indelen
  get "/indelen/:toernooiid" => "indelen#index"
  get "/indelen/:toernooiid/groep/:groepnummer" => "indelen#show"
  get "/indelen/:toernooiid/score" => "indelen#score"
  get "/indelen/:toernooiid/uitslag" => "indelen#uitslag"
  post "/indelen/:toernooiid" => "indelen#addingroep"
  post "/invoeren" => "indelen#invoeren"
  get "/indelen/:toernooiid/print" => "indelen#print"
  get "indelen/:toernooiid/tussenstand" => "indelen#tussenstand"

  root 'application#toernoois'
  get "/toernoois/:id/partijs" => "toernoois#partijs"

end

app/models/toernooi.rb
class Toernooi < ApplicationRecord
  validates :naam, :wedstrijdleider, :datum, presence: true

  has_many :groeps, :dependent => :destroy
  has_many :partijs, through: :groeps
  has_and_belongs_to_many :deelnemers
end

app/controllers/toernooi_controller.rb
class ToernooiController < ApplicationController
  
  def index
    @toernoois = Toernooi.all
  end

  def show
    @toernooi = Toernooi.find(params[:id])
  end


  def new
    @toernooi = Toernooi.new
  end
  def create
    @toernooi = Toernooi.new(toernooi_params)
    if @toernooi.save
      redirect_to :action => "new" #Waarheen?!
    else
      render :action => "new"
    end
  end

  def destroy
  end

  private

    def toernooi_params
      params.require(:toernooi).permit(:naam, :wedstrijdleider, :datum)
    end

end

app/controllers/toernoois_controller.rb
class ToernooisController < ApplicationController
  
  def index
    @toernoois = Toernooi.all
  end

  def show
    @toernooi = Toernooi.find(params[:id])
  end


  def new
    @toernooi = Toernooi.new
  end
  def create
    @toernooi = Toernooi.new(toernooi_params)
    if @toernooi.save
      @dzg = Groep.create(nummer: 0, toernooi_id: @toernooi.id)
      redirect_to @toernooi
    else
      render :action => "new"
    end
  end

  def destroy
    @toernooi = Toernooi.find(params[:id])
    @toernooi.destroy
    redirect_to toernoois_path
  end

  def partijs
    @toernooi = Toernooi.find(params[:id])
    @groeps = @toernooi.groeps.order("nummer").all
  end

  private

    def toernooi_params
      params.require(:toernooi).permit(:naam, :wedstrijdleider, :datum)
    end
    def deelnemer_params
      params.require(:deelnemer).permit(:voornaam, :achternaam, :tussenvoegsel, :geboortedatum)
    end

end

app/helpers/toernooi_helper.rb
module ToernooiHelper
end

app/views/toernoois/index.html.erb
<section>
  <h1>Alle Toernooien</h1>

  <table>
    <thead>
      <tr>
        <th>Naam</th>
        <th>Wedstrijdleider</th>
        <th>Datum</th>
        <th />
      </tr>

      <tbody>
        <% @toernoois.each do |toernooi| %>
          <tr>
            <td><%= link_to toernooi.naam, toernooi %></td>
            <td><%= toernooi.wedstrijdleider %></td>
            <td><%= toernooi.datum.strftime("%d-%m-%Y") %></td>
            <td><%= link_to "Laat zien", toernooi %></td>
          </tr>
        <% end %>
      </tbody>
    </thead>
  </table>

  <br />

  <%= link_to "Maak een Nieuw Toernooi", new_toernooi_path %>
</section>

app/views/toernoois/new.html.erb
<section>
  <h1>Nieuw Toernooi</h1>

  <% if @toernooi.errors.any? %>
    <%= @toernooi.errors.inspect %>
    <div style="border: 1px solid black">
      <h2><%= pluralize(@toernooi.errors.count, "fout") %> zijn gevonden:</h2>

      <ul>
      <% @toernooi.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= form_tag(controller: "toernoois", action: "create", method: "post") do %>
    <div class="input-field">
      <%= text_field(:toernooi, :naam) %>
      <label>Toernooinaam</label>
    </div>

    <div class="input-field">
      <%= text_field(:toernooi, :wedstrijdleider) %>
      <label>Wedstrijdleider</label>
    </div>

    <div>
      <label>Datum</label>
      <%= text_field(:toernooi, :datum, class: "datepicker") %>
    </div>

    <button class="btn waves-effect waves-light" type="submit" name="action">Submit
      <i class="material-icons right">send</i>
    </button>
  <% end %>
</section>

app/views/toernoois/partijs.html.erb
<% @groeps.each do |groep| %>
  <% next if groep.nummer.zero? %>
  <h1>Groep <%= groep.nummer %></h1>
  <% groep.partijs.each do |partij| %>
    <%= partij.witspeler.naam %> - <%= partij.zwartspeler.naam %> <br />
    <%= partij.uitslag %>
    <br />
    <hr />
    <br />
  <% end %>
<% end %>

app/views/toernoois/show.html.erb
<section>
  <h1><%= @toernooi.naam %></h1>
  <p>
    <b>Wedstrijdleider:</b> <%= @toernooi.wedstrijdleider %> </br>
    <b>Datum:</b> <%= @toernooi.datum.strftime("%d-%m-%Y") %>
  <p>

  <p>
    <%= link_to "Deel dit toernooi in", "/indelen/#{@toernooi.id}" %> </br>
    <%= link_to "Schrijf je in voor dit toernooi", action: "new", controller:"inschrijven" %> </br>
    <%= link_to "Inschrijflink voor deelnemers", "/aanmelden/#{@toernooi.id}" %><br />
    <%= link_to "Verwijder dit toernooi", @toernooi, method: :delete, data: {confirm: "Weet je het zeker? Alle gegevens zijn weg, en iedereen zal zich opnieuw moeten inschrijven."} %>
  </p>

  <article>
    <h2>Deelnemers (Aantal: <%= @toernooi.deelnemers.length %>)</h2>

    <table>
      <thead>
        <th>Naam</th>
        <th>Geboortedatum</th>
        <th>E-mail</th>
        <th>Telefoonnummer</th>
        <th>Rating</th>
        <th>KNSB nummer</th>
        <th></th>
      </thead>
      <tbody>
        <% @toernooi.deelnemers.each do |deelnemer| %>
          <tr>
            <td> <%= link_to deelnemer.naam, deelnemer %> </td>
            <td> <%= deelnemer.geboortedatum.strftime("%d-%m-%Y") %> </td>
            <td> <%= deelnemer.email||"" %> </td>
            <td> <%= deelnemer.telefoonnummer %> </td>
            <td> <%= deelnemer.rating||"" %> </td>
            <td> <%= deelnemer.knsbnummer||"" %> </td>
            <td> <%= link_to "Schrijf deze deelnemer uit", action:"destroy", controller:"inschrijven", toernooi_id: @toernooi.id,deelnemer_id: deelnemer.id %> </td>
          </tr>
        <% end %>
      <tbody/>
    </table>
  </article>
</section>